apiVersion: v1
kind: Service
metadata:
  name: zk-server
  labels:
    run: zk-server
spec:
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  selector:
    app: zk-server
---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: zk-server
 spec:
   replicas: 2
   selector:
     matchLabels:
       app: zk-server
   template:
     metadata:
       labels:
         app: zk-server
     spec:
      hostname: zk-server
      containers:
      - name: zk
        image: zookeeper
        imagePullPolicy: Never
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
