server:
  port: 8091

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: AQ
    topics:
      - name: AQ
        num-partitions: 1
        replication-factor: 3

---
spring:
  profiles: test
  kafka:
    producer:
      bootstrap-servers: localhost:9093
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: AQ
    topics:
    - name: AQ
      num-partitions: 1
      replication-factor: 3
